# permissions for end users to edit recipes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: recipe-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devconf-operator
    app.kubernetes.io/part-of: devconf-operator
    app.kubernetes.io/managed-by: kustomize
  name: recipe-editor-role
rules:
  - apiGroups:
      - devconfcz.opdev.com
    resources:
      - recipes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - devconfcz.opdev.com
    resources:
      - recipes/status
    verbs:
      - get
