apiVersion: devconfcz.opdev.com/v1alpha1
kind: Recipe
metadata:
  name: recipe-sample
spec:
  version: "v1.0.0"
  replicas: 2
  securityContext:
    runAsNonRoot: false
  podSecurityContext:
    runAsNonRoot: false
  hpa:
    minReplicas: 1
    maxReplicas: 2
    targetMemoryUtilization: 60
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi
  database:
    image: mysql:5.7
    securityContext:
      runAsNonRoot: false
    podSecurityContext:
      runAsNonRoot: false
