apiVersion: devconfcz.opdev.com/v1alpha1
kind: Recipe
metadata:
  name: recipe-sample
spec:
  # TODO(user): edit the following value to ensure the number
  # of Pods/Instances your Operand must have on cluster
  size: 1

  # TODO(user): edit the following value to ensure the container has the right port to be initialized
  containerPort: 5000
